export AR=/home/linuxbrew/.linuxbrew/bin/ar
export CC=/home/linuxbrew/.linuxbrew/bin/gcc-13
export CFLAGS=
export C_INCLUDE_PATH=/home/linuxbrew/.linuxbrew/include
export CPLUS_INCLUDE_PATH=/home/linuxbrew/.linuxbrew/include
export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/Cellar/bzip2/1.0.8/include"
export CXX=/home/linuxbrew/.linuxbrew/bin/g++-13
export GTK2_RC_FILES=/home/ben/.gtkrc-2.0-kde4
export GTK_RC_FILES=/etc/gtk/gtkrc:/home/ben/.gtkrc:/home/ben/.config/gtkrc
export HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
export HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
export INFOPATH=/home/linuxbrew/.linuxbrew/share/info:/home/linuxbrew/.linuxbrew/share/info:/home/linuxbrew/.linuxbrew/share/info:
export LANG=en_US.UTF-8
export LDFLAGS="-lm -ldl -lresolv"
export LD=/home/linuxbrew/.linuxbrew/bin/ld
export LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.49/lib:/home/linuxbrew/.linuxbrew/Cellar/pango/1.56.4/lib:/home/linuxbrew/.linuxbrew/Cellar/cairo/1.18.4/lib:/home/linuxbrew/.linuxbrew/Cellar/at-spi2-core/2.56.4/lib:/home/linuxbrew/.linuxbrew/Cellar/harfbuzz/11.4.1/lib:/home/linuxbrew/.linuxbrew/Cellar/glib/2.84.4/lib
export LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.49/lib:/home/linuxbrew/.linuxbrew/Cellar/pango/1.56.4/lib:/home/linuxbrew/.linuxbrew/Cellar/cairo/1.18.4/lib:/home/linuxbrew/.linuxbrew/Cellar/at-spi2-core/2.56.4/lib:/home/linuxbrew/.linuxbrew/Cellar/harfbuzz/11.4.1/lib:/home/linuxbrew/.linuxbrew/Cellar/glib/2.84.4/lib
export PIP_CONFIG_FILE=/home/ben/.config/pip/pip.conf
export PKG_CONFIG_PATH=/home/linuxbrew/.linuxbrew/lib/pkgconfig:/home/linuxbrew/.linuxbrew/share/pkgconfig:/home/linuxbrew/.linuxbrew/opt/xorgproto/share/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libx11/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxext/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libxrender/lib/pkgconfig
export RANLIB=/home/linuxbrew/.linuxbrew/bin/ranlib
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/deno/2.4.3/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/deno/2.4.3/.deno/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/java/zulu-21.42.19.0/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/mongodb/7.3.4/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/node/16.20.2/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/pnpm/7.32.2:/home/ben/dotfiles/local/xdgdata/mise/installs/python/3.13.7/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/r/4.5.0/bin:/home/ben/.cargo/bin:/home/ben/dotfiles/local/xdgdata/mise/installs/uv/0.8.11/uv-x86_64-unknown-linux-musl:/home/ben/dotfiles/local/xdgdata/mise/installs/yarn/1.22.22/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/ben/.local/bin:/home/ben/.nix-profile/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/ben/.local/bin:/home/ben/.nix-profile/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/ben/.local/bin:/home/ben/dotfiles/startup_shell/subcommands_bin:/home/ben/dotfiles/config/vscode/User/__bin:/home/ben/.local/yarn/bin:/home/ben/~/.nix-profile/bin:/home/ben/.local/bin:/home/ben/bin:/home/ben/myutils/mybin:/home/ben/.local/mybin:/usr/local/opt/openssl/bin:/home/ben/dotfiles/platforms/common:/home/ben/dotfiles/platforms/common/bin:.:/home/ben/.nix-profile/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ben/.config/Code/User/globalStorage/github.copilot-chat/debugCommand"
